name: Output Pipeline
on: workflow_dispatch
jobs:
    output:
        runs-on: ubuntu-latest
        steps:
            - name: output message
              run: echo "${{toJson(github)}} is running..."